project:
  type: website
  output-dir: docs

website:
  title: "BFI RSU resources"
  site-url: ""
  image: 'https://www.bfi.org.uk/dist/client/0207614d447715c2d2b9.svg'
  image-alt: Logo of British Film Institute
  open-graph: true
  repo-url: https://github.com/brtarran/report-table
  repo-actions: [edit, issue]
  navbar:
    background: "#e50076"
    logo: https://www.bfi.org.uk/dist/client/0207614d447715c2d2b9.svg
    logo-alt: Logo of British Film Institute
    left:
      - href: index.qmd
        text: Home

format:
  html:
    page-layout: full
    theme:
      - cosmo
      - assets/css/styles.scss
    css: assets/css/styles.css
    toc: true

execute:
  echo: false
  eval: true
  warning: false
  message: false
